package com.vrv.vap.xc.vo;

import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.plugin.QueryWapper;
import com.vrv.vap.toolkit.plugin.QueryWapperEnum;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table attack_info
 *
 * @mbg.generated do_not_delete_during_merge 2018-11-06 14:55:21
 */
@ApiModel
@SuppressWarnings("unused")
public class AttackInfoQuery extends Query {
    /**
     * 软件版本号信息
     */
    @ApiModelProperty("软件版本号信息")
    private String dtVersion;

    /**
     * 事件级别（10：非攻击事件 20：低级事件 30：中级事件  40：高级事件）
     */
    @ApiModelProperty("事件级别（10：非攻击事件 20：低级事件 30：中级事件  40：高级事件）")
    private Integer level;

    /**
     * 事件规则ID号，和特征库中的值相对应
     */
    @ApiModelProperty("事件规则ID号，和特征库中的值相对应")
    @NotNull
    private String id;

    /**
     * AlertLog
     */
    @ApiModelProperty("AlertLog")
    private String type;

    /**
     * 发生日志的时间
     */
    @ApiModelProperty("发生日志的时间")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.TIME_RANGE)
    private String tm;

    /**
     * 开始时间
     */
    private String startTimes;

    /**
     * 结束时间
     */
    private String endTimes;

    /**
     * 开始时间 dt时间分区
     */
    private String startDt;

    /**
     * 结束时间 dt时间分区
     */
    private String endDt;

    /**
     * 源ip地址
     */
    @ApiModelProperty("源ip地址")
    private String srcIp;

    /**
     * 源端口号
     */
    @ApiModelProperty("源端口号")
    private Long srcPort;

    /**
     * 源mac地址
     */
    @ApiModelProperty("源mac地址")
    private String srcMac;

    /**
     * 目标ip地址
     */
    @ApiModelProperty("目标ip地址")
    private String dstIp;

    /**
     * 目标端口号
     */
    @ApiModelProperty("目标端口号")
    private Long dstPort;

    /**
     * 目标mac地址
     */
    @ApiModelProperty("目标mac地址")
    private String dstMac;

    /**
     * 事件合并次数
     */
    @ApiModelProperty("事件合并次数")
    private Integer counts;

    /**
     * 协议的名字（取值TCP、UDP、ICMP等）
     */
    @ApiModelProperty("协议的名字（取值TCP、UDP、ICMP等）")
    private String protocol;

    /**
     * 事件名称
     */
    @ApiModelProperty("事件名称")
    private String subject;

    /**
     * 安全类型（参考附录1）
     */
    @ApiModelProperty("安全类型（参考附录1）")
    private String securityId;

    /**
     * 攻击类型（参考附录2）
     */
    @ApiModelProperty("攻击类型（参考附录2）")
    private String attackId;

    /**
     * 返回参数信息
     */
    @ApiModelProperty("返回参数信息")
    private String message;

    /**
     * 时间
     */
    @ApiModelProperty("时间")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.TIME_RANGE)
    private String dt;

    /**
     * 区域代码
     */
    @ApiModelProperty("区域代码")
    private String province;

    /**
     * 厂商
     */
    @ApiModelProperty("厂商")
    private String ajbProducer;

    /**
     * 整表数据来源IP
     */
    @ApiModelProperty("整表数据来源IP")
    private String ajbHost;

    /**
     * 接收时间
     */
    @ApiModelProperty("接收时间")
    private String vrvReceiveTime;

    /**
     * 源地区
     */
    @ApiModelProperty("源地区")
    private String srcArea;

    /**
     * 目标地区
     */
    @ApiModelProperty("目标地区")
    private String dstArea;

    public String getDtVersion() {
        return dtVersion;
    }

    public void setDtVersion(String dtVersion) {
        this.dtVersion = dtVersion;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTm() {
        return tm;
    }

    public void setTm(String tm) {
        this.tm = tm;
    }

    public String getSrcIp() {
        return srcIp;
    }

    public void setSrcIp(String srcIp) {
        this.srcIp = srcIp;
    }

    public Long getSrcPort() {
        return srcPort;
    }

    public void setSrcPort(Long srcPort) {
        this.srcPort = srcPort;
    }

    public String getSrcMac() {
        return srcMac;
    }

    public void setSrcMac(String srcMac) {
        this.srcMac = srcMac;
    }

    public String getDstIp() {
        return dstIp;
    }

    public void setDstIp(String dstIp) {
        this.dstIp = dstIp;
    }

    public Long getDstPort() {
        return dstPort;
    }

    public void setDstPort(Long dstPort) {
        this.dstPort = dstPort;
    }

    public String getDstMac() {
        return dstMac;
    }

    public void setDstMac(String dstMac) {
        this.dstMac = dstMac;
    }

    public Integer getCounts() {
        return counts;
    }

    public void setCounts(Integer counts) {
        this.counts = counts;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public String getSecurityId() {
        return securityId;
    }

    public void setSecurityId(String securityId) {
        this.securityId = securityId;
    }

    public String getAttackId() {
        return attackId;
    }

    public void setAttackId(String attackId) {
        this.attackId = attackId;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getDt() {
        return dt;
    }

    public void setDt(String dt) {
        this.dt = dt;
    }

    public String getProvince() {
        return province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getAjbProducer() {
        return ajbProducer;
    }

    public void setAjbProducer(String ajbProducer) {
        this.ajbProducer = ajbProducer;
    }

    public String getAjbHost() {
        return ajbHost;
    }

    public void setAjbHost(String ajbHost) {
        this.ajbHost = ajbHost;
    }

    public String getVrvReceiveTime() {
        return vrvReceiveTime;
    }

    public void setVrvReceiveTime(String vrvReceiveTime) {
        this.vrvReceiveTime = vrvReceiveTime;
    }

    public String getSrcArea() {
        return srcArea;
    }

    public void setSrcArea(String srcArea) {
        this.srcArea = srcArea;
    }

    public String getDstArea() {
        return dstArea;
    }

    public void setDstArea(String dstArea) {
        this.dstArea = dstArea;
    }

    public String getStartTimes() {
        return startTimes;
    }

    public void setStartTimes(String startTimes) {
        this.startTimes = startTimes;
    }

    public String getEndTimes() {
        return endTimes;
    }

    public void setEndTimes(String endTimes) {
        this.endTimes = endTimes;
    }

    public String getStartDt() {
        return startDt;
    }

    public void setStartDt(String startDt) {
        this.startDt = startDt;
    }

    public String getEndDt() {
        return endDt;
    }

    public void setEndDt(String endDt) {
        this.endDt = endDt;
    }
}