package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_sysinfo_database_user
 *
 * @mbg.generated do_not_delete_during_merge 2018-04-26 15:55:25
 */
@ApiModel
@SuppressWarnings("unused")
public class BaseSysinfoDatabaseUserQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 数据库ID
     */
    @ApiModelProperty("数据库ID")
    @NotNull
    private Integer databaseId;

    /**
     * 用户名
     */
    @ApiModelProperty("用户名")
    private String userName;

    /**
     * 数据源
     */
    @ApiModelProperty("数据源")
    private String soucre;

    /**
     * 责任人
     */
    @ApiModelProperty("责任人")
    private String personLiable;

    /**
     * 联系电话
     */
    @ApiModelProperty("联系电话")
    private String phone;

    /**
     * 责任人身份证号
     */
    @ApiModelProperty("责任人身份证号")
    private String useridn;

    /**
     * 是否巡检
     */
    @ApiModelProperty("是否巡检")
    private String isCheck;

    /**
     * 用户说明
     */
    @ApiModelProperty("用户说明")
    private String description;

    /**
     * 备注
     */
    @ApiModelProperty("备注")
    private String mark;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date lastUpdateTime;

    @ApiModelProperty("")
    private String sysId;

    /**
     * 数据库名
     */
    @ApiModelProperty("数据库名")
    private String databaseName;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getDatabaseId() {
        return databaseId;
    }

    public void setDatabaseId(Integer databaseId) {
        this.databaseId = databaseId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getSoucre() {
        return soucre;
    }

    public void setSoucre(String soucre) {
        this.soucre = soucre;
    }

    public String getPersonLiable() {
        return personLiable;
    }

    public void setPersonLiable(String personLiable) {
        this.personLiable = personLiable;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getUseridn() {
        return useridn;
    }

    public void setUseridn(String useridn) {
        this.useridn = useridn;
    }

    public String getIsCheck() {
        return isCheck;
    }

    public void setIsCheck(String isCheck) {
        this.isCheck = isCheck;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getMark() {
        return mark;
    }

    public void setMark(String mark) {
        this.mark = mark;
    }

    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public String getSysId() {
        return sysId;
    }

    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    public String getDatabaseName() {
        return databaseName;
    }

    public void setDatabaseName(String databaseName) {
        this.databaseName = databaseName;
    }
}