package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.plugin.QueryWapper;
import com.vrv.vap.toolkit.plugin.QueryWapperEnum;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table base_website_all
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-15 14:29:25
 */
@ApiModel
@SuppressWarnings("unused")
public class BaseWebsiteAllQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("url id")
    private Integer id;

    /**
     *
     */
    @ApiModelProperty("系统id")
    private Integer sid;

    /**
     * 完整url
     */
    @ApiModelProperty("完整url")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String url;

    /**
     * 父级url
     */
    @ApiModelProperty("父级url")
    private String purl;

    /**
     * 协议
     */
    @ApiModelProperty("协议")
    private String protocol;

    /**
     * 一级url
     */
    @ApiModelProperty("一级url")
    private String url1;

    /**
     * 二级url
     */
    @ApiModelProperty("二级url")
    private String url2;

    /**
     * 三级url
     */
    @ApiModelProperty("三级url")
    private String url3;

    /**
     * 四级url
     */
    @ApiModelProperty("四级url")
    private String url4;

    /**
     * 五级url
     */
    @ApiModelProperty("五级url")
    private String url5;

    /**
     * 服务器ip
     */
    @ApiModelProperty("服务器ip")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String serverIp;

    /**
     * url端口
     */
    @ApiModelProperty("url端口")
    private String port;

    /**
     * 0-未备案 1-已备案 2-软删除
     */
    @ApiModelProperty("0-未备案 1-已备案 2-软删除")
    private Integer state;

    /**
     * 发现时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("发现时间")
    private Date findTime;

    /**
     * 修改时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("修改时间")
    private Date updateTime;

    /**
     * 标签
     */
    @ApiModelProperty("标签")
    private String tags;

    /**
     * 区域
     */
    @ApiModelProperty("区域")
    private String areaCode;

    /**
     * url是否有效 1有效,0无效
     */
    @ApiModelProperty("url是否有效 1有效,0无效")
    private String isAlive;

    /**
     * 所属模块
     */
    @ApiModelProperty("所属模块")
    private String belong;

    /**
     * 网站标题
     */
    @ApiModelProperty("网站标题")
    private String title;

    /**
     * 0自动推断 1实际发现
     */
    @ApiModelProperty("0自动推断 1实际发现")
    private Integer fromType;

    /**
     * 级别 1 2 3 4 5
     */
    @ApiModelProperty("级别 1 2 3 4 5")
    private Integer level;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getPurl() {
        return purl;
    }

    public void setPurl(String purl) {
        this.purl = purl;
    }

    public String getProtocol() {
        return protocol;
    }

    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public String getUrl1() {
        return url1;
    }

    public void setUrl1(String url1) {
        this.url1 = url1;
    }

    public String getUrl2() {
        return url2;
    }

    public void setUrl2(String url2) {
        this.url2 = url2;
    }

    public String getUrl3() {
        return url3;
    }

    public void setUrl3(String url3) {
        this.url3 = url3;
    }

    public String getUrl4() {
        return url4;
    }

    public void setUrl4(String url4) {
        this.url4 = url4;
    }

    public String getUrl5() {
        return url5;
    }

    public void setUrl5(String url5) {
        this.url5 = url5;
    }

    public String getServerIp() {
        return serverIp;
    }

    public void setServerIp(String serverIp) {
        this.serverIp = serverIp;
    }

    public String getPort() {
        return port;
    }

    public void setPort(String port) {
        this.port = port;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getFindTime() {
        return findTime;
    }

    public void setFindTime(Date findTime) {
        this.findTime = findTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getIsAlive() {
        return isAlive;
    }

    public void setIsAlive(String isAlive) {
        this.isAlive = isAlive;
    }

    public String getBelong() {
        return belong;
    }

    public void setBelong(String belong) {
        this.belong = belong;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Integer getFromType() {
        return fromType;
    }

    public void setFromType(Integer fromType) {
        this.fromType = fromType;
    }

    public Integer getLevel() {
        return level;
    }

    public void setLevel(Integer level) {
        this.level = level;
    }

    public Integer getSid() {
        return sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }
}