package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_process_use
 *
 * @mbg.generated do_not_delete_during_merge 2019-09-11 15:46:58
 */
@ApiModel
@SuppressWarnings("unused")
public class BaseProcessUseQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 进程MD5值
     */
    @ApiModelProperty("进程MD5值")
    @NotNull
    private String md5;

    /**
     * 进程名
     */
    @ApiModelProperty("进程名")
    private String name;

    /**
     * 使用次数
     */
    @ApiModelProperty("使用次数")
    @NotNull
    private Integer count;

    /**
     * 使用率
     */
    @ApiModelProperty("使用率")
    private Double useRate;

    /**
     * 记录时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("记录时间")
    private Date recordTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public Double getUseRate() {
        return useRate;
    }

    public void setUseRate(Double useRate) {
        this.useRate = useRate;
    }

    public Date getRecordTime() {
        return recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}