package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_process
 *
 * @mbg.generated do_not_delete_during_merge 2019-09-11 15:39:30
 */
@ApiModel
@SuppressWarnings("unused")
public class BaseProcessQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *
     */
    @ApiModelProperty("")
    private String md5;

    /**
     *
     */
    @ApiModelProperty("")
    private String name;

    /**
     *
     */
    @ApiModelProperty("")
    private String signedName;

    /**
     *
     */
    @ApiModelProperty("")
    private String softwareName;

    /**
     *
     */
    @ApiModelProperty("")
    private String company;

    /**
     *
     */
    @ApiModelProperty("")
    private String version;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer isDisplay;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer isSuspicious;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer state;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer procTypeId;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer procChildrenTypeId;

    /**
     *
     */
    @ApiModelProperty("")
    private String description;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date firstFindTime;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date lastUpdateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSignedName() {
        return signedName;
    }

    public void setSignedName(String signedName) {
        this.signedName = signedName;
    }

    public String getSoftwareName() {
        return softwareName;
    }

    public void setSoftwareName(String softwareName) {
        this.softwareName = softwareName;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public Integer getIsDisplay() {
        return isDisplay;
    }

    public void setIsDisplay(Integer isDisplay) {
        this.isDisplay = isDisplay;
    }

    public Integer getIsSuspicious() {
        return isSuspicious;
    }

    public void setIsSuspicious(Integer isSuspicious) {
        this.isSuspicious = isSuspicious;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getProcTypeId() {
        return procTypeId;
    }

    public void setProcTypeId(Integer procTypeId) {
        this.procTypeId = procTypeId;
    }

    public Integer getProcChildrenTypeId() {
        return procChildrenTypeId;
    }

    public void setProcChildrenTypeId(Integer procChildrenTypeId) {
        this.procChildrenTypeId = procChildrenTypeId;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Date getFirstFindTime() {
        return firstFindTime;
    }

    public void setFirstFindTime(Date firstFindTime) {
        this.firstFindTime = firstFindTime;
    }

    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}