package com.vrv.vap.xc.vo;

import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_asset_ip_port_access
 *
 * @mbg.generated do_not_delete_during_merge 2019-06-10 09:50:35
 */
@ApiModel
@SuppressWarnings("unused")
public class BaseAssetIpPortAccessQuery extends Query {
    /**
     * 主键
     */
    @ApiModelProperty("主键")
    private Long id;

    /**
     * IP地址
     */
    @ApiModelProperty("IP地址")
    private String ip;

    /**
     * 端口确认日期
     */
    @ApiModelProperty("端口确认日期")
    private String date;

    /**
     * 开放的端口,绑定IP地址的设备开放的端口
     */
    @ApiModelProperty("开放的端口,绑定IP地址的设备开放的端口")
    private String openPort;

    /**
     * 访问类型：0访问，1被访问
     */
    @ApiModelProperty("访问类型：0访问，1被访问")
    private String accessType;

    /**
     * 访问次数
     */
    @ApiModelProperty("访问次数")
    private Long accessCount;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getOpenPort() {
        return openPort;
    }

    public void setOpenPort(String openPort) {
        this.openPort = openPort;
    }

    public String getAccessType() {
        return accessType;
    }

    public void setAccessType(String accessType) {
        this.accessType = accessType;
    }

    public Long getAccessCount() {
        return accessCount;
    }

    public void setAccessCount(Long accessCount) {
        this.accessCount = accessCount;
    }
}