package com.vrv.vap.xc.vo;

import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_city_area
 *
 * @mbg.generated do_not_delete_during_merge 2018-10-25 11:30:51
 */
@ApiModel
@SuppressWarnings("unused")
public class BaseCityAreaQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 地区编码（地市）
     */
    @ApiModelProperty("地区编码（地市）")
    private String areaCode;

    /**
     * 地区名称（地市）
     */
    @ApiModelProperty("地区名称（地市）")
    private String areaName;

    /**
     * 上级编码（省级）
     */
    @ApiModelProperty("上级编码（省级）")
    private String parentCode;

    /**
     * 上级名称（省级）
     */
    @ApiModelProperty("上级名称（省级）")
    private String parentName;

    /**
     * 备注
     */
    @ApiModelProperty("备注")
    private String remark;

    /**
     * IP段
     */
    @ApiModelProperty("IP段")
    private String ipRange;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getParentCode() {
        return parentCode;
    }

    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    public String getParentName() {
        return parentName;
    }

    public void setParentName(String parentName) {
        this.parentName = parentName;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getIpRange() {
        return ipRange;
    }

    public void setIpRange(String ipRange) {
        this.ipRange = ipRange;
    }
}