package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.math.BigDecimal;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table client_data_device
 *
 * @mbg.generated do_not_delete_during_merge 2019-07-15 13:56:20
 */
@ApiModel
@SuppressWarnings("unused")
public class ClientDataDeviceQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    @NotNull
    private String id;

    /**
     *
     */
    @ApiModelProperty("")
    private String ip;

    /**
     *
     */
    @ApiModelProperty("")
    private String ipType;

    /**
     *
     */
    @ApiModelProperty("")
    private String ipNumber;

    /**
     *
     */
    @ApiModelProperty("")
    private String mac;

    /**
     *
     */
    @ApiModelProperty("")
    private String name;

    /**
     *
     */
    @ApiModelProperty("")
    private String groupName;

    /**
     *
     */
    @ApiModelProperty("")
    private String description;

    /**
     *
     */
    @ApiModelProperty("")
    private String deviceType;

    /**
     *
     */
    @ApiModelProperty("")
    private String deviceUseful;

    /**
     *
     */
    @ApiModelProperty("")
    private String userName;

    /**
     *
     */
    @ApiModelProperty("")
    private String organization;

    /**
     *
     */
    @ApiModelProperty("")
    private String devOnlyId;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date registerTime;

    /**
     *
     */
    @ApiModelProperty("")
    private String clientId;

    /**
     *
     */
    @ApiModelProperty("")
    private String clientName;

    /**
     *
     */
    @ApiModelProperty("")
    private String clientVersion;

    /**
     *
     */
    @ApiModelProperty("")
    private String clientSign;

    /**
     *
     */
    @ApiModelProperty("")
    private String softVersion;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date unInstallTime;

    /**
     *
     */
    @ApiModelProperty("")
    private String switchIp;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer switchPort;

    /**
     *
     */
    @ApiModelProperty("")
    private String cpuType;

    /**
     *
     */
    @ApiModelProperty("")
    private BigDecimal cpuHz;

    /**
     *
     */
    @ApiModelProperty("")
    private BigDecimal memorySize;

    /**
     *
     */
    @ApiModelProperty("")
    private BigDecimal diskSize;

    /**
     *
     */
    @ApiModelProperty("")
    private String diskSerial;

    /**
     *
     */
    @ApiModelProperty("")
    private String computerManufacturer;

    /**
     *
     */
    @ApiModelProperty("")
    private String computerModel;

    /**
     *
     */
    @ApiModelProperty("")
    private String matherBoard;

    /**
     *
     */
    @ApiModelProperty("")
    private String serviceNo;

    /**
     *
     */
    @ApiModelProperty("")
    private String os;

    /**
     *
     */
    @ApiModelProperty("")
    private String isMutiOs;

    /**
     *
     */
    @ApiModelProperty("")
    private String isVm;

    /**
     *
     */
    @ApiModelProperty("")
    private String communicateIp;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer regState;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer protectState;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer deleteState;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer isOpened;

    /**
     *
     */
    @ApiModelProperty("")
    private String oldDevOnlyId;

    /**
     *
     */
    @ApiModelProperty("")
    private String location;

    /**
     * 日志设置
     */
    @ApiModelProperty("日志设置")
    private String logSetting;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getIpType() {
        return ipType;
    }

    public void setIpType(String ipType) {
        this.ipType = ipType;
    }

    public String getIpNumber() {
        return ipNumber;
    }

    public void setIpNumber(String ipNumber) {
        this.ipNumber = ipNumber;
    }

    public String getMac() {
        return mac;
    }

    public void setMac(String mac) {
        this.mac = mac;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public String getDeviceUseful() {
        return deviceUseful;
    }

    public void setDeviceUseful(String deviceUseful) {
        this.deviceUseful = deviceUseful;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getOrganization() {
        return organization;
    }

    public void setOrganization(String organization) {
        this.organization = organization;
    }

    public String getDevOnlyId() {
        return devOnlyId;
    }

    public void setDevOnlyId(String devOnlyId) {
        this.devOnlyId = devOnlyId;
    }

    public Date getRegisterTime() {
        return registerTime;
    }

    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientVersion() {
        return clientVersion;
    }

    public void setClientVersion(String clientVersion) {
        this.clientVersion = clientVersion;
    }

    public String getClientSign() {
        return clientSign;
    }

    public void setClientSign(String clientSign) {
        this.clientSign = clientSign;
    }

    public String getSoftVersion() {
        return softVersion;
    }

    public void setSoftVersion(String softVersion) {
        this.softVersion = softVersion;
    }

    public Date getUnInstallTime() {
        return unInstallTime;
    }

    public void setUnInstallTime(Date unInstallTime) {
        this.unInstallTime = unInstallTime;
    }

    public String getSwitchIp() {
        return switchIp;
    }

    public void setSwitchIp(String switchIp) {
        this.switchIp = switchIp;
    }

    public Integer getSwitchPort() {
        return switchPort;
    }

    public void setSwitchPort(Integer switchPort) {
        this.switchPort = switchPort;
    }

    public String getCpuType() {
        return cpuType;
    }

    public void setCpuType(String cpuType) {
        this.cpuType = cpuType;
    }

    public BigDecimal getCpuHz() {
        return cpuHz;
    }

    public void setCpuHz(BigDecimal cpuHz) {
        this.cpuHz = cpuHz;
    }

    public BigDecimal getMemorySize() {
        return memorySize;
    }

    public void setMemorySize(BigDecimal memorySize) {
        this.memorySize = memorySize;
    }

    public BigDecimal getDiskSize() {
        return diskSize;
    }

    public void setDiskSize(BigDecimal diskSize) {
        this.diskSize = diskSize;
    }

    public String getDiskSerial() {
        return diskSerial;
    }

    public void setDiskSerial(String diskSerial) {
        this.diskSerial = diskSerial;
    }

    public String getComputerManufacturer() {
        return computerManufacturer;
    }

    public void setComputerManufacturer(String computerManufacturer) {
        this.computerManufacturer = computerManufacturer;
    }

    public String getComputerModel() {
        return computerModel;
    }

    public void setComputerModel(String computerModel) {
        this.computerModel = computerModel;
    }

    public String getMatherBoard() {
        return matherBoard;
    }

    public void setMatherBoard(String matherBoard) {
        this.matherBoard = matherBoard;
    }

    public String getServiceNo() {
        return serviceNo;
    }

    public void setServiceNo(String serviceNo) {
        this.serviceNo = serviceNo;
    }

    public String getOs() {
        return os;
    }

    public void setOs(String os) {
        this.os = os;
    }

    public String getIsMutiOs() {
        return isMutiOs;
    }

    public void setIsMutiOs(String isMutiOs) {
        this.isMutiOs = isMutiOs;
    }

    public String getIsVm() {
        return isVm;
    }

    public void setIsVm(String isVm) {
        this.isVm = isVm;
    }

    public String getCommunicateIp() {
        return communicateIp;
    }

    public void setCommunicateIp(String communicateIp) {
        this.communicateIp = communicateIp;
    }

    public Integer getRegState() {
        return regState;
    }

    public void setRegState(Integer regState) {
        this.regState = regState;
    }

    public Integer getProtectState() {
        return protectState;
    }

    public void setProtectState(Integer protectState) {
        this.protectState = protectState;
    }

    public Integer getDeleteState() {
        return deleteState;
    }

    public void setDeleteState(Integer deleteState) {
        this.deleteState = deleteState;
    }

    public Integer getIsOpened() {
        return isOpened;
    }

    public void setIsOpened(Integer isOpened) {
        this.isOpened = isOpened;
    }

    public String getOldDevOnlyId() {
        return oldDevOnlyId;
    }

    public void setOldDevOnlyId(String oldDevOnlyId) {
        this.oldDevOnlyId = oldDevOnlyId;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getLogSetting() {
        return logSetting;
    }

    public void setLogSetting(String logSetting) {
        this.logSetting = logSetting;
    }
}