package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table conf_automatic_offline_tasks
 *
 * @mbg.generated do_not_delete_during_merge 2018-06-25 10:09:33
 */
@ApiModel
@SuppressWarnings("unused")
public class ConfAutomaticOfflineTasksQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    @NotNull
    private Date creatTime;

    /**
     *
     */
    @ApiModelProperty("")
    @NotNull
    private String taskDetail;

    /**
     *
     */
    @ApiModelProperty("")
    @NotNull
    private String type;

    /**
     *
     */
    @ApiModelProperty("")
    private String taskName;

    /**
     *
     */
    @ApiModelProperty("")
    private String oozieId;

    /**
     * 周期时间
     */
    @ApiModelProperty("周期时间")
    private String cycleTime;

    /**
     * 任务是否删除 0删除1正常
     */
    @ApiModelProperty("任务是否删除 0删除1正常")
    private String deleteFlag;

    /**
     * 是否需要邮件推送
     */
    @ApiModelProperty("是否需要邮件推送")
    private String isEmail;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getCreatTime() {
        return creatTime;
    }

    public void setCreatTime(Date creatTime) {
        this.creatTime = creatTime;
    }

    public String getTaskDetail() {
        return taskDetail;
    }

    public void setTaskDetail(String taskDetail) {
        this.taskDetail = taskDetail;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTaskName() {
        return taskName;
    }

    public void setTaskName(String taskName) {
        this.taskName = taskName;
    }

    public String getOozieId() {
        return oozieId;
    }

    public void setOozieId(String oozieId) {
        this.oozieId = oozieId;
    }

    public String getCycleTime() {
        return cycleTime;
    }

    public void setCycleTime(String cycleTime) {
        this.cycleTime = cycleTime;
    }

    public String getDeleteFlag() {
        return deleteFlag;
    }

    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    public String getIsEmail() {
        return isEmail;
    }

    public void setIsEmail(String isEmail) {
        this.isEmail = isEmail;
    }
}