package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.plugin.QueryWapper;
import com.vrv.vap.toolkit.plugin.QueryWapperEnum;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table data_moniotr_error_log
 *
 * @mbg.generated do_not_delete_during_merge 2020-12-25 16:56:20
 */
@ApiModel
@SuppressWarnings("unused")
public class DataMoniotrErrorLogQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    @NotNull
    private String id;

    /**
     * 时间范围
     */
    @ApiModelProperty("时间范围")
    private String timeRange;

    /**
     * 厂商
     */
    @ApiModelProperty("厂商")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String company;

    /**
     * 数据类型
     */
    @ApiModelProperty("数据类型")
    private String type;

    /**
     * 时间段内平均数据量
     */
    @ApiModelProperty("时间段内平均数据量")
    private Long avgCount;

    /**
     * 数据量详情
     */
    @ApiModelProperty("数据量详情")
    private String detail;

    /**
     * 记录时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("记录时间")
    @NotNull
    private Date logTime;

    /**
     * 上限占比阈值
     */
    @ApiModelProperty("上限占比阈值")
    private String upThreshold;

    /**
     * 下限占比阈值
     */
    @ApiModelProperty("下限占比阈值")
    private String downThreshold;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTimeRange() {
        return timeRange;
    }

    public void setTimeRange(String timeRange) {
        this.timeRange = timeRange;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getAvgCount() {
        return avgCount;
    }

    public void setAvgCount(Long avgCount) {
        this.avgCount = avgCount;
    }

    public String getDetail() {
        return detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public Date getLogTime() {
        return logTime;
    }

    public void setLogTime(Date logTime) {
        this.logTime = logTime;
    }

    public String getUpThreshold() {
        return upThreshold;
    }

    public void setUpThreshold(String upThreshold) {
        this.upThreshold = upThreshold;
    }

    public String getDownThreshold() {
        return downThreshold;
    }

    public void setDownThreshold(String downThreshold) {
        this.downThreshold = downThreshold;
    }
}