package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table dossier_psn_obj
 *
 * @mbg.generated do_not_delete_during_merge 2018-12-13 18:24:16
 */
@ApiModel
@SuppressWarnings("unused")
public class DossierPsnObjQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Long id;

    /**
     * 身份证号码
     */
    @ApiModelProperty("身份证号码")
    private String idCard;

    /**
     * 姓名
     */
    @ApiModelProperty("姓名")
    private String username;

    /**
     * 对象类型编号
     */
    @ApiModelProperty("对象类型编号")
    private Integer objectType;

    /**
     * 对象内容
     */
    @ApiModelProperty("对象内容")
    private String content;

    /**
     * 对象被查询次数
     */
    @ApiModelProperty("对象被查询次数")
    private Integer count;

    /**
     * 年月
     */
    @ApiModelProperty("年月")
    private String timeG;

    /**
     * 记录时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("记录时间")
    private Date recordTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public Integer getObjectType() {
        return objectType;
    }

    public void setObjectType(Integer objectType) {
        this.objectType = objectType;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getCount() {
        return count;
    }

    public void setCount(Integer count) {
        this.count = count;
    }

    public String getTimeG() {
        return timeG;
    }

    public void setTimeG(String timeG) {
        this.timeG = timeG;
    }

    public Date getRecordTime() {
        return recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}