package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table early_warn_app_visit
 *
 * @mbg.generated do_not_delete_during_merge 2018-05-31 18:01:29
 */
@ApiModel
@SuppressWarnings("unused")
public class EarlyWarnAppVisitQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 姓名
     */
    @ApiModelProperty("姓名")
    private String username;

    /**
     * 身份证
     */
    @ApiModelProperty("身份证")
    private String userId;

    /**
     * 各系统访问详情
     */
    @ApiModelProperty("各系统访问详情")
    private String sysDetail;

    /**
     * 访问总量
     */
    @ApiModelProperty("访问总量")
    private Integer total;

    /**
     * 类型，1-上班访问预警，2-下班访问预警
     */
    @ApiModelProperty("类型，1-上班访问预警，2-下班访问预警")
    private Integer warnType;

    /**
     * 预警时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("预警时间")
    private Date warnTime;

    /**
     * 地区
     */
    @ApiModelProperty("地区")
    private String areaCode;

    /**
     * 数据时间
     */
    @ApiModelProperty("数据时间")
    private String dataTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getSysDetail() {
        return sysDetail;
    }

    public void setSysDetail(String sysDetail) {
        this.sysDetail = sysDetail;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public Integer getWarnType() {
        return warnType;
    }

    public void setWarnType(Integer warnType) {
        this.warnType = warnType;
    }

    public Date getWarnTime() {
        return warnTime;
    }

    public void setWarnTime(Date warnTime) {
        this.warnTime = warnTime;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getDataTime() {
        return dataTime;
    }

    public void setDataTime(String dataTime) {
        this.dataTime = dataTime;
    }
}