package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ew_anomaly_access_detail
 *
 * @mbg.generated do_not_delete_during_merge 2019-11-07 16:42:50
 */
@ApiModel
@SuppressWarnings("unused")
public class EwAnomalyAccessDetailQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    @NotNull
    private String id;

    /**
     *
     */
    @ApiModelProperty("")
    private String resultGuid;

    /**
     *
     */
    @ApiModelProperty("")
    private String relatedIps;

    /**
     *
     */
    @ApiModelProperty("")
    private String username;

    /**
     *
     */
    @ApiModelProperty("")
    private String userId;

    /**
     *
     */
    @ApiModelProperty("")
    private String areaCode;

    /**
     *
     */
    @ApiModelProperty("")
    private String ruleCode;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date triggerTime;

    /**
     *
     */
    @ApiModelProperty("")
    private String sysId;

    /**
     *
     */
    @ApiModelProperty("")
    private String policeType;

    /**
     *
     */
    @ApiModelProperty("")
    private String organization;

    /**
     *
     */
    @ApiModelProperty("")
    private String operateCondition;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getResultGuid() {
        return resultGuid;
    }

    public void setResultGuid(String resultGuid) {
        this.resultGuid = resultGuid;
    }

    public String getRelatedIps() {
        return relatedIps;
    }

    public void setRelatedIps(String relatedIps) {
        this.relatedIps = relatedIps;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getRuleCode() {
        return ruleCode;
    }

    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }

    public Date getTriggerTime() {
        return triggerTime;
    }

    public void setTriggerTime(Date triggerTime) {
        this.triggerTime = triggerTime;
    }

    public String getSysId() {
        return sysId;
    }

    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    public String getPoliceType() {
        return policeType;
    }

    public void setPoliceType(String policeType) {
        this.policeType = policeType;
    }

    public String getOrganization() {
        return organization;
    }

    public void setOrganization(String organization) {
        this.organization = organization;
    }

    public String getOperateCondition() {
        return operateCondition;
    }

    public void setOperateCondition(String operateCondition) {
        this.operateCondition = operateCondition;
    }
}