package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hive_backup_log
 *
 * @mbg.generated do_not_delete_during_merge 2021-03-18 14:29:44
 */
@ApiModel
@SuppressWarnings("unused")
public class HiveBackupLogQuery extends Query {
    /**
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *   hive表名
     */
    @ApiModelProperty("hive表名")
    @NotNull
    private String tableName;

    /**
     *   文件路径
     */
    @ApiModelProperty("文件路径")
    @NotNull
    private String filePath;

    /**
     *   描述
     */
    @ApiModelProperty("描述")
    private String description;

    /**
     *   存储模式: 0 SFTP 1 共享目录
     */
    @ApiModelProperty("存储模式: 0 SFTP 1 共享目录")
    private Integer saveModel;

    /**
     *   时间字段名
     */
    @ApiModelProperty("时间字段名")
    @NotNull
    private String timeField;

    /**
     *   数据时间
     */
    @ApiModelProperty("数据时间")
    private String dataDate;

    /**
     *   备份时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("备份时间")
    private Date recordTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getSaveModel() {
        return saveModel;
    }

    public void setSaveModel(Integer saveModel) {
        this.saveModel = saveModel;
    }

    public String getTimeField() {
        return timeField;
    }

    public void setTimeField(String timeField) {
        this.timeField = timeField;
    }

    public String getDataDate() {
        return dataDate;
    }

    public void setDataDate(String dataDate) {
        this.dataDate = dataDate;
    }

    public Date getRecordTime() {
        return recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}