package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hive_clean_log
 *
 * @mbg.generated do_not_delete_during_merge 2021-03-18 11:25:54
 */
@ApiModel
@SuppressWarnings("unused")
public class HiveCleanLogQuery extends Query {
    /**
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *   hive表名
     */
    @ApiModelProperty("hive表名")
    @NotNull
    private String tableName;

    /**
     *   描述
     */
    @ApiModelProperty("描述")
    private String description;

    /**
     *   触发清理模式：0常规清理，1磁盘预警
     */
    @ApiModelProperty("触发清理模式：0常规清理，1磁盘预警")
    private Integer deleteModel;

    /**
     *   备份时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("备份时间")
    private Date cleanTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getDeleteModel() {
        return deleteModel;
    }

    public void setDeleteModel(Integer deleteModel) {
        this.deleteModel = deleteModel;
    }

    public Date getCleanTime() {
        return cleanTime;
    }

    public void setCleanTime(Date cleanTime) {
        this.cleanTime = cleanTime;
    }
}