package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table hive_policy
 *
 * @mbg.generated do_not_delete_during_merge 2021-03-17 13:57:13
 */
@ApiModel
@SuppressWarnings("unused")
public class HivePolicyQuery extends Query {
    /**
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *   hive表名
     */
    @ApiModelProperty("hive表名")
    @NotNull
    private String tableName;

    /**
     *   时间字段名
     */
    @ApiModelProperty("时间字段名")
    @NotNull
    private String timeField;

    /**
     *   保存数据时间 3 三个月，6 六个月，12 十二个月
     */
    @ApiModelProperty("保存数据时间 3 三个月，6 六个月，12 十二个月")
    @NotNull
    private String dataTime;

    /**
     *   清理模式: 0 只清理不备份 1 先备份后清理
     */
    @ApiModelProperty("清理模式: 0 只清理不备份 1 先备份后清理")
    private Integer cleanMode;

    /**
     *   存储模式: 0 SFTP 1 共享目录
     */
    @ApiModelProperty("存储模式: 0 SFTP 1 共享目录")
    private Integer saveMode;

    /**
     *   状态: 0 关闭 1 开启
     */
    @ApiModelProperty("状态: 0 关闭 1 开启")
    private Integer status;

    /**
     *   创建时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("创建时间")
    private Date createTime;

    /**
     *   备注
     */
    @ApiModelProperty("备注")
    private String description;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTableName() {
        return tableName;
    }

    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getTimeField() {
        return timeField;
    }

    public void setTimeField(String timeField) {
        this.timeField = timeField;
    }

    public String getDataTime() {
        return dataTime;
    }

    public void setDataTime(String dataTime) {
        this.dataTime = dataTime;
    }

    public Integer getCleanMode() {
        return cleanMode;
    }

    public void setCleanMode(Integer cleanMode) {
        this.cleanMode = cleanMode;
    }

    public Integer getSaveMode() {
        return saveMode;
    }

    public void setSaveMode(Integer saveMode) {
        this.saveMode = saveMode;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}