package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;
import java.util.List;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table label_mark
 *
 * @mbg.generated do_not_delete_during_merge 2018-11-14 17:50:14
 */
@ApiModel
@SuppressWarnings("unused")
public class LabelMarkQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Long id;

    private String ids;

    /**
     * 标签名称表 主键ID
     */
    @ApiModelProperty("标签名称表 主键ID")
    private String labelConfId;

    private List<String> labelConfIdList;

    public String getIds() {
        return ids;
    }

    public void setIds(String ids) {
        this.ids = ids;
    }

    public List<String> getLabelConfIdList() {
        return labelConfIdList;
    }

    public void setLabelConfIdList(List<String> labelConfIdList) {
        this.labelConfIdList = labelConfIdList;
    }

    /**
     * 0 人 1 设备 2 应用
     */
    @ApiModelProperty("0 人 1 设备 2 应用")
    private String objType;

    /**
     * 业务场景类别 0 基于模型 1 基于规则 2 基于统计分析 3 自定义
     */
    @ApiModelProperty("业务场景类别 0 基于模型 1 基于规则 2 基于统计分析 3 自定义")
    private String type;

    /**
     * 人 设备 应用唯一标识
     */
    @ApiModelProperty("人 设备 应用唯一标识")
    private String objKey;

    /**
     * 标签最新时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("标签最新时间")
    private Date lastUpdateTime;

    /**
     * 最后一次打标签人ID
     */
    @ApiModelProperty("最后一次打标签人ID")
    private String lastSourceId;

    /**
     * 最后一次打标签名称
     */
    @ApiModelProperty("最后一次打标签名称")
    private String lastSourceName;

    /**
     * 标签次数
     */
    @ApiModelProperty("标签次数")
    private Long labelCount;

    /**
     *
     */
    @ApiModelProperty("")
    private Long version;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLabelConfId() {
        return labelConfId;
    }

    public void setLabelConfId(String labelConfId) {
        this.labelConfId = labelConfId;
    }

    public String getObjType() {
        return objType;
    }

    public void setObjType(String objType) {
        this.objType = objType;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getObjKey() {
        return objKey;
    }

    public void setObjKey(String objKey) {
        this.objKey = objKey;
    }

    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public String getLastSourceId() {
        return lastSourceId;
    }

    public void setLastSourceId(String lastSourceId) {
        this.lastSourceId = lastSourceId;
    }

    public String getLastSourceName() {
        return lastSourceName;
    }

    public void setLastSourceName(String lastSourceName) {
        this.lastSourceName = lastSourceName;
    }

    public Long getLabelCount() {
        return labelCount;
    }

    public void setLabelCount(Long labelCount) {
        this.labelCount = labelCount;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }
}