package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table netflow_warn
 *
 * @mbg.generated do_not_delete_during_merge 2021-04-27 09:37:29
 */
@ApiModel
@SuppressWarnings("unused")
public class NetflowWarnQuery extends Query {
    /**
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 预警时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd")
    @ApiModelProperty("预警时间")
    private Date warnTime;

    /**
     * 预警主体
     */
    @ApiModelProperty("预警主体")
    private String warnSubject;

    /**
     * 预警类型
     */
    @ApiModelProperty("预警类型")
    private String warnType;

    /**
     * 预警描述
     */
    @ApiModelProperty("预警描述")
    private String warnDesc;

    /**
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date insertTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Date getWarnTime() {
        return warnTime;
    }

    public void setWarnTime(Date warnTime) {
        this.warnTime = warnTime;
    }

    public String getWarnSubject() {
        return warnSubject;
    }

    public void setWarnSubject(String warnSubject) {
        this.warnSubject = warnSubject;
    }

    public String getWarnType() {
        return warnType;
    }

    public void setWarnType(String warnType) {
        this.warnType = warnType;
    }

    public String getWarnDesc() {
        return warnDesc;
    }

    public void setWarnDesc(String warnDesc) {
        this.warnDesc = warnDesc;
    }

    public Date getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}