package com.vrv.vap.xc.vo;

import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table olt_queryobj
 *
 * @mbg.generated do_not_delete_during_merge 2020-10-27 15:29:54
 */
@ApiModel
@SuppressWarnings("unused")
public class OltQueryobjQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 任务ID
     */
    @ApiModelProperty("任务ID")
    private String taskId;

    /**
     * 区域
     */
    @ApiModelProperty("区域")
    private String areaName;

    /**
     * 身份证
     */
    @ApiModelProperty("身份证")
    private String idCard;

    /**
     * 姓名
     */
    @ApiModelProperty("姓名")
    private String userName;

    /**
     * 系统
     */
    @ApiModelProperty("系统")
    private String sysId;

    /**
     * 单位
     */
    @ApiModelProperty("单位")
    private String org;

    /**
     * 次数
     */
    @ApiModelProperty("次数")
    private Integer total;

    /**
     * 首次查询时间
     */
    @ApiModelProperty("首次查询时间")
    private String operateFirstTime;

    /**
     * 最近查询时间
     */
    @ApiModelProperty("最近查询时间")
    private String operateLastTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTaskId() {
        return taskId;
    }

    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getIdCard() {
        return idCard;
    }

    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getSysId() {
        return sysId;
    }

    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    public String getOrg() {
        return org;
    }

    public void setOrg(String org) {
        this.org = org;
    }

    public Integer getTotal() {
        return total;
    }

    public void setTotal(Integer total) {
        this.total = total;
    }

    public String getOperateFirstTime() {
        return operateFirstTime;
    }

    public void setOperateFirstTime(String operateFirstTime) {
        this.operateFirstTime = operateFirstTime;
    }

    public String getOperateLastTime() {
        return operateLastTime;
    }

    public void setOperateLastTime(String operateLastTime) {
        this.operateLastTime = operateLastTime;
    }
}