package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.plugin.QueryWapper;
import com.vrv.vap.toolkit.plugin.QueryWapperEnum;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table repository_process
 *
 * @mbg.generated do_not_delete_during_merge 2019-09-11 17:48:00
 */
@ApiModel
@SuppressWarnings("unused")
public class RepositoryProcessQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 进程MD5值
     */
    @ApiModelProperty("进程MD5值")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String processName;

    /**
     * 进程说明
     */
    @ApiModelProperty("进程说明")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String processDesc;

    /**
     * 进程MD5值
     */
    @ApiModelProperty("进程MD5值")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String md5;

    /**
     * 进程版本
     */
    @ApiModelProperty("进程版本")
    private String version;

    /**
     * 软件名称
     */
    @ApiModelProperty("软件名称")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String softwareName;

    /**
     * 签名
     */
    @ApiModelProperty("签名")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String signName;

    /**
     * 公司
     */
    @ApiModelProperty("公司")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.LIKE)
    private String company;

    /**
     * 软件类别
     */
    @ApiModelProperty("软件类别")
    private Integer classId;

    /**
     * 软件类别名称
     */
    @ApiModelProperty("软件类别名称")
    private String className;

    /**
     * 进程分类
     */
    @ApiModelProperty("进程分类")
    private Integer appClassId;

    /**
     * 进程分类名称
     */
    @ApiModelProperty("进程分类名称")
    private String appClassName;

    /**
     * 软件名称
     */
    @ApiModelProperty("软件名称")
    private String areaCode;

    /**
     * 软件名称
     */
    @ApiModelProperty("软件名称")
    private String areaName;

    /**
     * 类别
     */
    @ApiModelProperty("类别")
    private Integer type;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date insertTime;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date lastUpdateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getProcessName() {
        return processName;
    }

    public void setProcessName(String processName) {
        this.processName = processName;
    }

    public String getProcessDesc() {
        return processDesc;
    }

    public void setProcessDesc(String processDesc) {
        this.processDesc = processDesc;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getSoftwareName() {
        return softwareName;
    }

    public void setSoftwareName(String softwareName) {
        this.softwareName = softwareName;
    }

    public String getSignName() {
        return signName;
    }

    public void setSignName(String signName) {
        this.signName = signName;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public Integer getClassId() {
        return classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public String getClassName() {
        return className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public Integer getAppClassId() {
        return appClassId;
    }

    public void setAppClassId(Integer appClassId) {
        this.appClassId = appClassId;
    }

    public String getAppClassName() {
        return appClassName;
    }

    public void setAppClassName(String appClassName) {
        this.appClassName = appClassName;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Date getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }
}