package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rpt_app_abnormal_netflow
 *
 * @mbg.generated do_not_delete_during_merge 2020-08-27 17:22:12
 */
@ApiModel
@SuppressWarnings("unused")
public class RptAppAbnormalNetflowQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 应用Id
     */
    @ApiModelProperty("应用Id")
    private String sysId;

    /**
     * ip(多个逗号分隔)
     */
    @ApiModelProperty("ip(多个逗号分隔)")
    private String ip;

    /**
     *
     */
    @ApiModelProperty("")
    private String sysName;

    /**
     * 安全域
     */
    @ApiModelProperty("安全域")
    private String safetyMargin;

    /**
     * 总流量
     */
    @ApiModelProperty("总流量")
    private Long total;

    /**
     * 用于计算均值的总流量
     */
    @ApiModelProperty("用于计算均值的总流量")
    private Long cTotal;

    /**
     * 上传流量
     */
    @ApiModelProperty("上传流量")
    private Long uploadTotal;

    /**
     * 用于计算均值的上传流量
     */
    @ApiModelProperty("用于计算均值的上传流量")
    private Long cUploadTotal;

    /**
     * 下行流量
     */
    @ApiModelProperty("下行流量")
    private Long downloadTotal;

    /**
     * 用于计算均值的下行流量
     */
    @ApiModelProperty("用于计算均值的下行流量")
    private Long cDownloadTotal;

    /**
     * 总流量均值
     */
    @ApiModelProperty("总流量均值")
    private Long avgTotal;

    /**
     * 上行流量均值
     */
    @ApiModelProperty("上行流量均值")
    private Long avgUploadTotal;

    /**
     * 下行流量均值
     */
    @ApiModelProperty("下行流量均值")
    private Long avgDownloadTotal;

    /**
     * 数据时间(yyyyMMdd)
     */
    @ApiModelProperty("数据时间(yyyyMMdd)")
    private String dataTime;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date recordTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSysId() {
        return sysId;
    }

    public void setSysId(String sysId) {
        this.sysId = sysId;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public String getSysName() {
        return sysName;
    }

    public void setSysName(String sysName) {
        this.sysName = sysName;
    }

    public String getSafetyMargin() {
        return safetyMargin;
    }

    public void setSafetyMargin(String safetyMargin) {
        this.safetyMargin = safetyMargin;
    }

    public Long getTotal() {
        return total;
    }

    public void setTotal(Long total) {
        this.total = total;
    }

    public Long getcTotal() {
        return cTotal;
    }

    public void setcTotal(Long cTotal) {
        this.cTotal = cTotal;
    }

    public Long getUploadTotal() {
        return uploadTotal;
    }

    public void setUploadTotal(Long uploadTotal) {
        this.uploadTotal = uploadTotal;
    }

    public Long getcUploadTotal() {
        return cUploadTotal;
    }

    public void setcUploadTotal(Long cUploadTotal) {
        this.cUploadTotal = cUploadTotal;
    }

    public Long getDownloadTotal() {
        return downloadTotal;
    }

    public void setDownloadTotal(Long downloadTotal) {
        this.downloadTotal = downloadTotal;
    }

    public Long getcDownloadTotal() {
        return cDownloadTotal;
    }

    public void setcDownloadTotal(Long cDownloadTotal) {
        this.cDownloadTotal = cDownloadTotal;
    }

    public Long getAvgTotal() {
        return avgTotal;
    }

    public void setAvgTotal(Long avgTotal) {
        this.avgTotal = avgTotal;
    }

    public Long getAvgUploadTotal() {
        return avgUploadTotal;
    }

    public void setAvgUploadTotal(Long avgUploadTotal) {
        this.avgUploadTotal = avgUploadTotal;
    }

    public Long getAvgDownloadTotal() {
        return avgDownloadTotal;
    }

    public void setAvgDownloadTotal(Long avgDownloadTotal) {
        this.avgDownloadTotal = avgDownloadTotal;
    }

    public String getDataTime() {
        return dataTime;
    }

    public void setDataTime(String dataTime) {
        this.dataTime = dataTime;
    }

    public Date getRecordTime() {
        return recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}