package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.plugin.QueryWapper;
import com.vrv.vap.toolkit.plugin.QueryWapperEnum;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rpt_abnormal_netflow
 *
 * @mbg.generated do_not_delete_during_merge 2020-07-02 11:06:17
 */
@ApiModel
@SuppressWarnings("unused")
public class RptAbnormalNetflowQuery extends Query {
    /**
     * 主键/自增长
     */
    @ApiModelProperty("主键/自增长")
    private Long id;

    /**
     * IP或者应用Id
     */
    @ApiModelProperty("IP或者应用Id")
    private String subject;

    /**
     * 访问量
     */
    @ApiModelProperty("访问量")
    private Integer visitCount;

    /**
     * IP个数
     */
    @ApiModelProperty("IP个数")
    private Integer ipCount;

    /**
     * 类型1=互联网源地址异常流量分析,2=目标应用异常流量分析,3=外连流量异常分析
     */
    @ApiModelProperty("类型1=互联网源地址异常流量分析,2=目标应用异常流量分析,3=外连流量异常分析")
    private Integer type;

    /**
     * 数据时间
     */
    @ApiModelProperty("数据时间")
    @QueryWapper(queryWapperEnum = QueryWapperEnum.IGNORE)
    private String dataTime;

    /**
     * 入库时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("入库时间")
    private Date recordTime;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public Integer getVisitCount() {
        return visitCount;
    }

    public void setVisitCount(Integer visitCount) {
        this.visitCount = visitCount;
    }

    public Integer getIpCount() {
        return ipCount;
    }

    public void setIpCount(Integer ipCount) {
        this.ipCount = ipCount;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getDataTime() {
        return dataTime;
    }

    public void setDataTime(String dataTime) {
        this.dataTime = dataTime;
    }

    public Date getRecordTime() {
        return recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}