package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rpt_device_error
 *
 * @mbg.generated do_not_delete_during_merge 2019-11-27 11:56:28
 */
@ApiModel
@SuppressWarnings("unused")
public class RptDeviceErrorQuery extends Query {
    /**
     * 主键
     */
    @ApiModelProperty("主键")
    private Integer id;

    /**
     * 脱缰数量
     */
    @ApiModelProperty("脱缰数量")
    private Integer regno;

    /**
     * 注册状态异常数量
     */
    @ApiModelProperty("注册状态异常数量")
    private Integer noreg;

    /**
     * 无杀毒软件数量
     */
    @ApiModelProperty("无杀毒软件数量")
    private Integer novirus;

    /**
     * 使用人与注册人不同数量
     */
    @ApiModelProperty("使用人与注册人不同数量")
    private Integer userwrong;

    /**
     * 违规保护/信任数量
     */
    @ApiModelProperty("违规保护/信任数量")
    private Integer noprono;

    /**
     * 长期未用数量
     */
    @ApiModelProperty("长期未用数量")
    private Integer nouse;

    /**
     * 无效设备数量
     */
    @ApiModelProperty("无效设备数量")
    private Integer novali;

    /**
     * 无效组中正常设备数量
     */
    @ApiModelProperty("无效组中正常设备数量")
    private Integer normal;

    /**
     * 地区
     */
    @ApiModelProperty("地区")
    private String areaCode;

    /**
     * 主键
     */
    @ApiModelProperty("主键")
    private Integer nover;

    /**
     * 记录时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd")
    @ApiModelProperty("记录时间")
    private Date recordTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getRegno() {
        return regno;
    }

    public void setRegno(Integer regno) {
        this.regno = regno;
    }

    public Integer getNoreg() {
        return noreg;
    }

    public void setNoreg(Integer noreg) {
        this.noreg = noreg;
    }

    public Integer getNovirus() {
        return novirus;
    }

    public void setNovirus(Integer novirus) {
        this.novirus = novirus;
    }

    public Integer getUserwrong() {
        return userwrong;
    }

    public void setUserwrong(Integer userwrong) {
        this.userwrong = userwrong;
    }

    public Integer getNoprono() {
        return noprono;
    }

    public void setNoprono(Integer noprono) {
        this.noprono = noprono;
    }

    public Integer getNouse() {
        return nouse;
    }

    public void setNouse(Integer nouse) {
        this.nouse = nouse;
    }

    public Integer getNovali() {
        return novali;
    }

    public void setNovali(Integer novali) {
        this.novali = novali;
    }

    public Integer getNormal() {
        return normal;
    }

    public void setNormal(Integer normal) {
        this.normal = normal;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public Integer getNover() {
        return nover;
    }

    public void setNover(Integer nover) {
        this.nover = nover;
    }

    public Date getRecordTime() {
        return recordTime;
    }

    public void setRecordTime(Date recordTime) {
        this.recordTime = recordTime;
    }
}