package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table spcl_rpt_ukn_asset
 *
 * @mbg.generated do_not_delete_during_merge 2021-03-08 17:43:49
 */
@ApiModel
@SuppressWarnings("unused")
public class SpclRptUknAssetQuery extends Query {
    /**
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *   通报周期
     */
    @ApiModelProperty("通报周期")
    private String reportWeek;

    /**
     *   设备ip
     */
    @ApiModelProperty("设备ip")
    private String ip;

    /**
     *   是否应用资产:1.疑似,0不是
     */
    @ApiModelProperty("是否应用资产:1.疑似,0不是")
    private Integer assetType;

    /**
     *   区域
     */
    @ApiModelProperty("区域")
    private String areaCode;

    /**
     *   url
     */
    @ApiModelProperty("url")
    private String url;

    /**
     *   添加时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("添加时间")
    private Date insertTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getReportWeek() {
        return reportWeek;
    }

    public void setReportWeek(String reportWeek) {
        this.reportWeek = reportWeek;
    }

    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public Integer getAssetType() {
        return assetType;
    }

    public void setAssetType(Integer assetType) {
        this.assetType = assetType;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public Date getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}