package com.vrv.vap.xc.vo;

import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table synthesis_netflow
 *
 * @mbg.generated do_not_delete_during_merge 2019-01-10 15:11:29
 */
@ApiModel
@SuppressWarnings("unused")
public class SynthesisNetflowQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 地区编码
     */
    @ApiModelProperty("地区编码")
    @NotNull
    private String areaCode;

    /**
     * 访问流量总量
     */
    @ApiModelProperty("访问流量总量")
    @NotNull
    private Long visitBytesTotal;

    /**
     * 上行流量包总量
     */
    @ApiModelProperty("上行流量包总量")
    @NotNull
    private Long uploadPkgTotal;

    /**
     * 被访问流量总量
     */
    @ApiModelProperty("被访问流量总量")
    @NotNull
    private Long visitedBytesTotal;

    /**
     * 下行流量包总量
     */
    @ApiModelProperty("下行流量包总量")
    @NotNull
    private Long downloadPkgTotal;

    /**
     * 平均访问流量
     */
    @ApiModelProperty("平均访问流量")
    private Long avgVisitTrafficBytes;

    /**
     * 平均被访问流量
     */
    @ApiModelProperty("平均被访问流量")
    private Long avgVisitedTrafficBytes;

    /**
     * 日期
     */
    @ApiModelProperty("日期")
    @NotNull
    private String dataTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public Long getVisitBytesTotal() {
        return visitBytesTotal;
    }

    public void setVisitBytesTotal(Long visitBytesTotal) {
        this.visitBytesTotal = visitBytesTotal;
    }

    public Long getUploadPkgTotal() {
        return uploadPkgTotal;
    }

    public void setUploadPkgTotal(Long uploadPkgTotal) {
        this.uploadPkgTotal = uploadPkgTotal;
    }

    public Long getVisitedBytesTotal() {
        return visitedBytesTotal;
    }

    public void setVisitedBytesTotal(Long visitedBytesTotal) {
        this.visitedBytesTotal = visitedBytesTotal;
    }

    public Long getDownloadPkgTotal() {
        return downloadPkgTotal;
    }

    public void setDownloadPkgTotal(Long downloadPkgTotal) {
        this.downloadPkgTotal = downloadPkgTotal;
    }

    public Long getAvgVisitTrafficBytes() {
        return avgVisitTrafficBytes;
    }

    public void setAvgVisitTrafficBytes(Long avgVisitTrafficBytes) {
        this.avgVisitTrafficBytes = avgVisitTrafficBytes;
    }

    public Long getAvgVisitedTrafficBytes() {
        return avgVisitedTrafficBytes;
    }

    public void setAvgVisitedTrafficBytes(Long avgVisitedTrafficBytes) {
        this.avgVisitedTrafficBytes = avgVisitedTrafficBytes;
    }

    public String getDataTime() {
        return dataTime;
    }

    public void setDataTime(String dataTime) {
        this.dataTime = dataTime;
    }
}