package com.vrv.vap.xc.vo;

import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table synthesis_risk_evaluation
 *
 * @mbg.generated do_not_delete_during_merge 2018-12-13 17:29:11
 */
@ApiModel
@SuppressWarnings("unused")
public class SynthesisRiskEvaluationQuery extends Query {
    /**
     *
     */
    @ApiModelProperty("")
    private Long id;

    /**
     * 网络流量风险值
     */
    @ApiModelProperty("网络流量风险值")
    @NotNull
    private Double netflowRisk;

    /**
     * 攻击风险值
     */
    @ApiModelProperty("攻击风险值")
    @NotNull
    private Double attackRisk;

    /**
     * 热点应用系统访问风险值
     */
    @ApiModelProperty("热点应用系统访问风险值")
    private Double hotspotAccessRisk;

    /**
     * 病毒文件风险值
     */
    @ApiModelProperty("病毒文件风险值")
    private Double virusRisk;

    /**
     * 脆弱性风险值
     */
    @ApiModelProperty("脆弱性风险值")
    private Double vulnerabilityRisk;

    /**
     * 威胁情报风险值
     */
    @ApiModelProperty("威胁情报风险值")
    private Double threatRisk;

    /**
     * 综合态势评估值
     */
    @ApiModelProperty("综合态势评估值")
    private Double synthesisRiskEvaluation;

    /**
     * 评估日期
     */
    @ApiModelProperty("评估日期")
    private String yyyymmdd;

    /**
     * 设备IP区域码
     */
    @ApiModelProperty("设备IP区域码")
    private String areaCode;

    /**
     * 区域名称
     */
    @ApiModelProperty("区域名称")
    private String areaName;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Double getNetflowRisk() {
        return netflowRisk;
    }

    public void setNetflowRisk(Double netflowRisk) {
        this.netflowRisk = netflowRisk;
    }

    public Double getAttackRisk() {
        return attackRisk;
    }

    public void setAttackRisk(Double attackRisk) {
        this.attackRisk = attackRisk;
    }

    public Double getHotspotAccessRisk() {
        return hotspotAccessRisk;
    }

    public void setHotspotAccessRisk(Double hotspotAccessRisk) {
        this.hotspotAccessRisk = hotspotAccessRisk;
    }

    public Double getVirusRisk() {
        return virusRisk;
    }

    public void setVirusRisk(Double virusRisk) {
        this.virusRisk = virusRisk;
    }

    public Double getVulnerabilityRisk() {
        return vulnerabilityRisk;
    }

    public void setVulnerabilityRisk(Double vulnerabilityRisk) {
        this.vulnerabilityRisk = vulnerabilityRisk;
    }

    public Double getThreatRisk() {
        return threatRisk;
    }

    public void setThreatRisk(Double threatRisk) {
        this.threatRisk = threatRisk;
    }

    public Double getSynthesisRiskEvaluation() {
        return synthesisRiskEvaluation;
    }

    public void setSynthesisRiskEvaluation(Double synthesisRiskEvaluation) {
        this.synthesisRiskEvaluation = synthesisRiskEvaluation;
    }

    public String getYyyymmdd() {
        return yyyymmdd;
    }

    public void setYyyymmdd(String yyyymmdd) {
        this.yyyymmdd = yyyymmdd;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }
}