package com.vrv.vap.xc.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.toolkit.vo.Query;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rules_result
 *
 * @mbg.generated do_not_delete_during_merge 2018-07-20 11:40:13
 */
@ApiModel
@SuppressWarnings("unused")
public class WarnResultQuery extends Query {
    /**
     * 主键
     */
    @ApiModelProperty("主键")
    @NotNull
    private String id;

    /**
     *
     */
    @ApiModelProperty("")
    private String riskEventName;

    /**
     *
     */
    @ApiModelProperty("")
    private String ruleId;

    /**
     *
     */
    @ApiModelProperty("")
    private String ruleName;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date triggerTime;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer analysisType;

    /**
     * 处理状态：0-待确认、1-已确认、2-已处置、3-误报、4-待下发、5-已接受、6-已接收
     */
    @ApiModelProperty("处理状态：0-待确认、1-已确认、2-已处置、3-误报、4-待下发、5-已接受、6-已接收")
    private Integer statusEnum;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer processTypeEnum;

    /**
     * 知识库id集合
     */
    @ApiModelProperty("知识库id集合")
    private String knowIds;

    /**
     * 知识库名称集合
     */
    @ApiModelProperty("知识库名称集合")
    private String knowNames;

    /**
     *
     */
    @ApiModelProperty("")
    private String processRelateId;

    /**
     * 权重
     */
    @ApiModelProperty("权重")
    @NotNull
    private Integer weight;

    /**
     * 源ip集合
     */
    @ApiModelProperty("源ip集合")
    private String relatedIps;

    /**
     * 安全域guids
     */
    @ApiModelProperty("安全域guids")
    private String securityDomainGuids;

    /**
     * 安全域名称
     */
    @ApiModelProperty("安全域名称")
    private String securityDomainNames;

    /**
     * 告警事件详情json
     */
    @ApiModelProperty("告警事件详情json")
    private String logsInfo;

    /**
     * 目标ip集合
     */
    @ApiModelProperty("目标ip集合")
    private String dstIps;

    /**
     * 目标资产guids
     */
    @ApiModelProperty("目标资产guids")
    private String dstAssetGuids;

    /**
     * 目标安全域guids
     */
    @ApiModelProperty("目标安全域guids")
    private String dstSecurityDomainGuids;

    /**
     * 目标安全域名称
     */
    @ApiModelProperty("目标安全域名称")
    private String dstSecurityDomainNames;

    /**
     * 备注
     */
    @ApiModelProperty("备注")
    private String marks;

    /**
     * 告警事件编码,证书违规使用（编码：/safer/business/pkiuse）、违规外联（编码：/safer/business/outreach）、危险进程发现（编码：/safer/business/illegalprocess）、游戏进程发现（编码：/safer/business/gameprocess）、红名单查询（编码：/safer/business/red）、热点库查询（编码：/safer/business/hot）
     */
    @ApiModelProperty("告警事件编码,证书违规使用（编码：/safer/business/pkiuse）、违规外联（编码：/safer/business/outreach）、危险进程发现（编码：/safer/business/illegalprocess）、游戏进程发现（编码：/safer/business/gameprocess）、红名单查询（编码：/safer/business/red）、热点库查询（编码：/safer/business/hot）")
    private String riskEventCode;

    /**
     * 优先级
     */
    @ApiModelProperty("优先级")
    private String priorityLevel;

    /**
     * 资产guids
     */
    @ApiModelProperty("资产guids")
    private String assetGuids;

    /**
     * 事件分类
     */
    @ApiModelProperty("事件分类")
    private String eventType;

    /**
     * 事件分类级别
     */
    @ApiModelProperty("事件分类级别")
    private String eventTypeLevel;

    /**
     * 设备分类
     */
    @ApiModelProperty("设备分类")
    private String deviceType;

    /**
     * 设备分类级别
     */
    @ApiModelProperty("设备分类级别")
    private String deviceTypeLevel;

    /**
     * 告警唯一标识
     */
    @ApiModelProperty("告警唯一标识")
    @NotNull
    private String resultGuid;

    /**
     * 告警编码
     */
    @ApiModelProperty("告警编码")
    @NotNull
    private String ruleCode;

    /**
     * 姓名
     */
    @ApiModelProperty("姓名")
    @NotNull
    private String username;

    /**
     * 身份证
     */
    @ApiModelProperty("身份证")
    @NotNull
    private String userId;

    /**
     * 地区编码
     */
    @ApiModelProperty("地区编码")
    @NotNull
    private String areaCode;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getRiskEventName() {
        return riskEventName;
    }

    public void setRiskEventName(String riskEventName) {
        this.riskEventName = riskEventName;
    }

    public String getRuleId() {
        return ruleId;
    }

    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }

    public String getRuleName() {
        return ruleName;
    }

    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    public Date getTriggerTime() {
        return triggerTime;
    }

    public void setTriggerTime(Date triggerTime) {
        this.triggerTime = triggerTime;
    }

    public Integer getAnalysisType() {
        return analysisType;
    }

    public void setAnalysisType(Integer analysisType) {
        this.analysisType = analysisType;
    }

    public Integer getStatusEnum() {
        return statusEnum;
    }

    public void setStatusEnum(Integer statusEnum) {
        this.statusEnum = statusEnum;
    }

    public Integer getProcessTypeEnum() {
        return processTypeEnum;
    }

    public void setProcessTypeEnum(Integer processTypeEnum) {
        this.processTypeEnum = processTypeEnum;
    }

    public String getKnowIds() {
        return knowIds;
    }

    public void setKnowIds(String knowIds) {
        this.knowIds = knowIds;
    }

    public String getKnowNames() {
        return knowNames;
    }

    public void setKnowNames(String knowNames) {
        this.knowNames = knowNames;
    }

    public String getProcessRelateId() {
        return processRelateId;
    }

    public void setProcessRelateId(String processRelateId) {
        this.processRelateId = processRelateId;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public String getRelatedIps() {
        return relatedIps;
    }

    public void setRelatedIps(String relatedIps) {
        this.relatedIps = relatedIps;
    }

    public String getSecurityDomainGuids() {
        return securityDomainGuids;
    }

    public void setSecurityDomainGuids(String securityDomainGuids) {
        this.securityDomainGuids = securityDomainGuids;
    }

    public String getSecurityDomainNames() {
        return securityDomainNames;
    }

    public void setSecurityDomainNames(String securityDomainNames) {
        this.securityDomainNames = securityDomainNames;
    }

    public String getLogsInfo() {
        return logsInfo;
    }

    public void setLogsInfo(String logsInfo) {
        this.logsInfo = logsInfo;
    }

    public String getDstIps() {
        return dstIps;
    }

    public void setDstIps(String dstIps) {
        this.dstIps = dstIps;
    }

    public String getDstAssetGuids() {
        return dstAssetGuids;
    }

    public void setDstAssetGuids(String dstAssetGuids) {
        this.dstAssetGuids = dstAssetGuids;
    }

    public String getDstSecurityDomainGuids() {
        return dstSecurityDomainGuids;
    }

    public void setDstSecurityDomainGuids(String dstSecurityDomainGuids) {
        this.dstSecurityDomainGuids = dstSecurityDomainGuids;
    }

    public String getDstSecurityDomainNames() {
        return dstSecurityDomainNames;
    }

    public void setDstSecurityDomainNames(String dstSecurityDomainNames) {
        this.dstSecurityDomainNames = dstSecurityDomainNames;
    }

    public String getMarks() {
        return marks;
    }

    public void setMarks(String marks) {
        this.marks = marks;
    }

    public String getRiskEventCode() {
        return riskEventCode;
    }

    public void setRiskEventCode(String riskEventCode) {
        this.riskEventCode = riskEventCode;
    }

    public String getPriorityLevel() {
        return priorityLevel;
    }

    public void setPriorityLevel(String priorityLevel) {
        this.priorityLevel = priorityLevel;
    }

    public String getAssetGuids() {
        return assetGuids;
    }

    public void setAssetGuids(String assetGuids) {
        this.assetGuids = assetGuids;
    }

    public String getEventType() {
        return eventType;
    }

    public void setEventType(String eventType) {
        this.eventType = eventType;
    }

    public String getEventTypeLevel() {
        return eventTypeLevel;
    }

    public void setEventTypeLevel(String eventTypeLevel) {
        this.eventTypeLevel = eventTypeLevel;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public String getDeviceTypeLevel() {
        return deviceTypeLevel;
    }

    public void setDeviceTypeLevel(String deviceTypeLevel) {
        this.deviceTypeLevel = deviceTypeLevel;
    }

    public String getResultGuid() {
        return resultGuid;
    }

    public void setResultGuid(String resultGuid) {
        this.resultGuid = resultGuid;
    }

    public String getRuleCode() {
        return ruleCode;
    }

    public void setRuleCode(String ruleCode) {
        this.ruleCode = ruleCode;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }
}