package com.vrv.vap.alarmdeal.frameworks.contract.audit;

import io.swagger.annotations.ApiModel;

/**
 *
 * This class was generated by MyBatis Generator. This class corresponds to the
 * database table base_sysinfo_server
 *
 * @mbg.generated do_not_delete_during_merge 2018-04-18 10:57:53
 */
@ApiModel
public class BaseSysinfoServer {
	/**
	 */
	@io.swagger.annotations.ApiModelProperty("")
	private Integer id;

	/**
	 * 系统id
	 */
	@io.swagger.annotations.ApiModelProperty("系统id")
	private Integer sysId;

	/**
	 * 应用系统名称#手动添加字段非自动生成
	 */
	@io.swagger.annotations.ApiModelProperty("应用系统名称")
	private String sysName;

	/**
	 * 服务器ip
	 */
	@io.swagger.annotations.ApiModelProperty("服务器ip")
	private String ip;

	/**
	 * 服务器操作系统:windows 2000;windows server 2008;windows xp;linux;windows 7;windows
	 * 8.1;windows 10;others;
	 */
	@io.swagger.annotations.ApiModelProperty("服务器操作系统:windows 2000;windows server 2008;windows xp;linux;windows 7;windows 8.1;windows 10;others;")
//	@Effective({ "windows 2000", "windows server 2008", "windows xp", "linux", "windows 7", "windows 8.1", "windows 10",
//			"others" })
	private String os;

	/**
	 * 服务器类型:其他;应用服务器;数据库服务器;单相光设备;ftp服务器;备份服务器;NAS存储;存储;保垒机;应用数据库服务器;新版测试服务器;交换机设备;代理服务器、数据库服务器;
	 */
	@io.swagger.annotations.ApiModelProperty("服务器类型:其他;应用服务器;数据库服务器;单相光设备;ftp服务器;备份服务器;NAS存储;存储;保垒机;应用数据库服务器;新版测试服务器;交换机设备;代理服务器、数据库服务器;")
//	@Effective({ "其他", "应用服务器", "数据库服务器", "单相光设备", "ftp服务器", "备份服务器", "NAS存储", "存储", "保垒机", "应用数据库服务器", "新版测试服务器",
//			"交换机设备", "代理服务器、数据库服务器", "" })
	private String serverType;

	/**
	 * 描述
	 */
	@io.swagger.annotations.ApiModelProperty("描述")
	private String description;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getSysId() {
		return sysId;
	}

	public void setSysId(Integer sysId) {
		this.sysId = sysId;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getOs() {
		return os;
	}

	public void setOs(String os) {
		this.os = os;
	}

	public String getServerType() {
		return serverType;
	}

	public void setServerType(String serverType) {
		this.serverType = serverType;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getSysName() {
		return sysName;
	}

	public void setSysName(String sysName) {
		this.sysName = sysName;
	}
}