package com.vrv.vap.amonitor.model.es;

import com.vrv.vap.amonitor.model.PageModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table discover_index
 *
 * @mbg.generated do_not_delete_during_merge 2020-11-19 16:13:53
 */
@ApiModel
@SuppressWarnings("unused")
public class DiscoverIndex extends PageModel {
    /**
     * 主键
     */
    @ApiModelProperty("主键")
    private Integer id;

    /**
     * 索引id
     */
    @ApiModelProperty("索引id")
    private String indexId;

    /**
     * 索引名称
     */
    @ApiModelProperty("索引名称")
    private String indexName;

    /**
     * 索引类型
     */
    @ApiModelProperty("索引类型")
    private String type;

    /**
     * 索引名称
     */
    @ApiModelProperty("索引名称")
    private String title;

    /**
     * 索引描述
     */
    @ApiModelProperty("索引描述")
    private String titleDesc;

    /**
     * 时间字段
     */
    @ApiModelProperty("时间字段")
    private String timeFieldName;

    /**
     * 是否默认索引 1：是，0：否
     */
    @ApiModelProperty("是否默认索引 1：是，0：否")
    private Integer defaultIndex;

    /**
     * 类别-用来检索入库量统计
     */
    @ApiModelProperty("类别-用来检索入库量统计")
    private String category;

    /**
     * 安全域字段
     */
    @ApiModelProperty("安全域字段")
    private String domainFieldName;

    /**
     * 索引字段
     */
    @ApiModelProperty("索引字段")
    private String indexFields;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getIndexId() {
        return indexId;
    }

    public void setIndexId(String indexId) {
        this.indexId = indexId;
    }

    public String getIndexName() {
        return indexName;
    }

    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitleDesc() {
        return titleDesc;
    }

    public void setTitleDesc(String titleDesc) {
        this.titleDesc = titleDesc;
    }

    public String getTimeFieldName() {
        return timeFieldName;
    }

    public void setTimeFieldName(String timeFieldName) {
        this.timeFieldName = timeFieldName;
    }

    public Integer getDefaultIndex() {
        return defaultIndex;
    }

    public void setDefaultIndex(Integer defaultIndex) {
        this.defaultIndex = defaultIndex;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getDomainFieldName() {
        return domainFieldName;
    }

    public void setDomainFieldName(String domainFieldName) {
        this.domainFieldName = domainFieldName;
    }

    public String getIndexFields() {
        return indexFields;
    }

    public void setIndexFields(String indexFields) {
        this.indexFields = indexFields;
    }
}