package com.vrv.vap.xc.pojo;

import com.vrv.vap.xc.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_area
 *
 * @mbg.generated do_not_delete_during_merge 2021-02-24 14:22:52
 */
@ApiModel
@SuppressWarnings("unused")
public class BaseArea extends BaseModel {
    /**
     *
     */
    @ApiModelProperty("")
    private Long id;

    /**
     * 区域编码
     */
    @ApiModelProperty("区域编码")
    private String areaCode;

    /**
     * 区域名称
     */
    @ApiModelProperty("区域名称")
    private String areaName;

    /**
     * ip范围
     */
    @ApiModelProperty("ip范围")
    private String ipRange;

    /**
     * 上级编号
     */
    @ApiModelProperty("上级编号")
    private String parentCode;

    /**
     * 描述
     */
    @ApiModelProperty("描述")
    private String description;

    /**
     * 截取编码（确认地区）
     */
    @ApiModelProperty("截取编码（确认地区）")
    private String areaCodeSub;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer sort;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getAreaName() {
        return areaName;
    }

    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    public String getIpRange() {
        return ipRange;
    }

    public void setIpRange(String ipRange) {
        this.ipRange = ipRange;
    }

    public String getParentCode() {
        return parentCode;
    }

    public void setParentCode(String parentCode) {
        this.parentCode = parentCode;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAreaCodeSub() {
        return areaCodeSub;
    }

    public void setAreaCodeSub(String areaCodeSub) {
        this.areaCodeSub = areaCodeSub;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

}