package com.vrv.vap.xc.pojo;

import com.vrv.vap.xc.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_dict_all
 *
 * @mbg.generated do_not_delete_during_merge 2018-09-30 17:11:43
 */
@ApiModel
@SuppressWarnings("unused")
public class BaseDictAll extends BaseModel {
    /**
     *
     */
    @ApiModelProperty("")
    private Long id;

    /**
     * 字典表编号
     */
    @ApiModelProperty("字典表编号")
    private String code;

    /**
     * 字典表名称
     */
    @ApiModelProperty("字典表名称")
    private String codeValue;

    /**
     * 字典表类型
     */
    @ApiModelProperty("字典表类型")
    private String type;

    /**
     * 父类型
     */
    @ApiModelProperty("父类型")
    private String parentType;

    /**
     * 是否是叶子节点
     */
    @ApiModelProperty("是否是叶子节点")
    private String leaf;

    /**
     * 描述
     */
    @ApiModelProperty("描述")
    private String description;

    /**
     * 创建人ID
     */
    @ApiModelProperty("创建人ID")
    private String createId;

    /**
     * 创建时间
     */
    @ApiModelProperty("创建时间")
    private String createTime;

    /**
     * 更新人ID
     */
    @ApiModelProperty("更新人ID")
    private String updateId;

    /**
     * 更新时间
     */
    @ApiModelProperty("更新时间")
    private String updateTime;

    /**
     * 排序
     */
    @ApiModelProperty("排序")
    private Integer sort;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCodeValue() {
        return codeValue;
    }

    public void setCodeValue(String codeValue) {
        this.codeValue = codeValue;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getParentType() {
        return parentType;
    }

    public void setParentType(String parentType) {
        this.parentType = parentType;
    }

    public String getLeaf() {
        return leaf;
    }

    public void setLeaf(String leaf) {
        this.leaf = leaf;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getUpdateId() {
        return updateId;
    }

    public void setUpdateId(String updateId) {
        this.updateId = updateId;
    }

    public String getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }
}