package com.vrv.vap.xc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.toolkit.annotations.NotNull;
import com.vrv.vap.xc.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table data_dump_strategy
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-07 16:50:30
 */
@ApiModel
@SuppressWarnings("unused")
public class DataDumpStrategy extends BaseModel {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 数据类型，1-es 2-mysql 3-hive 4-hbase
     */
    @ApiModelProperty("数据类型，1-es 2-mysql 3-hive 4-hbase")
    private Integer dataType;

    /**
     * 数据标识
     */
    @ApiModelProperty("数据标识")
    private String dataId;

    /**
     * 数据描述
     */
    @ApiModelProperty("数据描述")
    private String dataDesc;

    /**
     * 数据保存时间，单位：天
     */
    @ApiModelProperty("数据保存时间，单位：天")
    private Integer saveTime;

    /**
     * 清理模式，1-只清理不备份，2-先备份后清理
     */
    @ApiModelProperty("清理模式，1-只清理不备份，2-先备份后清理")
    private Integer type;

    /**
     * 转储方式，1-手动下载，2-sftp，3-共享目录
     */
    @ApiModelProperty("转储方式，1-手动下载，2-sftp，3-共享目录")
    private Integer dumpMode;

    /**
     * 状态，1-启用，0-关闭
     */
    @ApiModelProperty("状态，1-启用，0-关闭")
    private Integer state;

    /**
     * 创建时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("创建时间")
    @NotNull
    private Date createTime;

    /**
     * 最后修改时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("最后修改时间")
    @NotNull
    private Date updateTime;

    /**
     * 备注
     */
    @ApiModelProperty("备注")
    private String remark;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getDataType() {
        return dataType;
    }

    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    public String getDataId() {
        return dataId;
    }

    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    public String getDataDesc() {
        return dataDesc;
    }

    public void setDataDesc(String dataDesc) {
        this.dataDesc = dataDesc;
    }

    public Integer getSaveTime() {
        return saveTime;
    }

    public void setSaveTime(Integer saveTime) {
        this.saveTime = saveTime;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public Integer getDumpMode() {
        return dumpMode;
    }

    public void setDumpMode(Integer dumpMode) {
        this.dumpMode = dumpMode;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}