package com.vrv.vap.xc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.xc.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table data_dump_log
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-07 16:45:13
 */
@ApiModel
@SuppressWarnings("unused")
public class DataDumpLog extends BaseModel {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     * 策略编号
     */
    @ApiModelProperty("策略编号")
    private Integer strategyId;

    /**
     * 数据类型，1-es 2-mysql 3-hive 4-hbase
     */
    @ApiModelProperty("数据类型，1-es 2-mysql 3-hive 4-hbase")
    private Integer dataType;

    /**
     * 数据标识
     */
    @ApiModelProperty("数据标识")
    private String dataId;

    /**
     * 数据描述
     */
    @ApiModelProperty("数据描述")
    private String dataDesc;

    /**
     * 具体数据
     */
    @ApiModelProperty("具体数据")
    private String dataDetail;

    /**
     * 快照标识
     */
    @ApiModelProperty("快照标识")
    private String snapshotName;

    /**
     * 备份时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("备份时间")
    private Date dumpTime;

    /**
     * 备份文件路径
     */
    @ApiModelProperty("备份文件路径")
    private String dumpFilePath;

    /**
     * 备份文件状态，1-存在，0-已删除
     */
    @ApiModelProperty("备份文件状态，1-存在，0-已删除")
    private Integer dumpFileState;

    /**
     * 备份文件MD5值
     */
    @ApiModelProperty("备份文件MD5值")
    private String dumpFileMd5;

    /**
     * 备注
     */
    @ApiModelProperty("备注")
    private String remark;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getStrategyId() {
        return strategyId;
    }

    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }

    public Integer getDataType() {
        return dataType;
    }

    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    public String getDataId() {
        return dataId;
    }

    public void setDataId(String dataId) {
        this.dataId = dataId;
    }

    public String getDataDesc() {
        return dataDesc;
    }

    public void setDataDesc(String dataDesc) {
        this.dataDesc = dataDesc;
    }

    public String getDataDetail() {
        return dataDetail;
    }

    public void setDataDetail(String dataDetail) {
        this.dataDetail = dataDetail;
    }

    public String getSnapshotName() {
        return snapshotName;
    }

    public void setSnapshotName(String snapshotName) {
        this.snapshotName = snapshotName;
    }

    public Date getDumpTime() {
        return dumpTime;
    }

    public void setDumpTime(Date dumpTime) {
        this.dumpTime = dumpTime;
    }

    public String getDumpFilePath() {
        return dumpFilePath;
    }

    public void setDumpFilePath(String dumpFilePath) {
        this.dumpFilePath = dumpFilePath;
    }

    public Integer getDumpFileState() {
        return dumpFileState;
    }

    public void setDumpFileState(Integer dumpFileState) {
        this.dumpFileState = dumpFileState;
    }

    public String getDumpFileMd5() {
        return dumpFileMd5;
    }

    public void setDumpFileMd5(String dumpFileMd5) {
        this.dumpFileMd5 = dumpFileMd5;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}