package com.vrv.vap.xc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.xc.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table kafka_operate_log
 *
 * @mbg.generated do_not_delete_during_merge 2021-01-15 11:36:08
 */
@ApiModel
@SuppressWarnings("unused")
public class KafkaOperateLog extends BaseModel {
    /**
     * 主键
     */
    @ApiModelProperty("主键")
    private Integer id;

    /**
     * 命令
     */
    @ApiModelProperty("命令")
    private String cmd;

    /**
     * 执行信息
     */
    @ApiModelProperty("执行信息")
    private String message;

    /**
     * 命令类型
     */
    @ApiModelProperty("命令类型")
    private Integer cmdType;

    /**
     * 命令类型名称
     */
    @ApiModelProperty("命令类型名称")
    private String cmdTypeName;

    /**
     * 主题
     */
    @ApiModelProperty("主题")
    private String kafkaTopic;

    /**
     * 执行时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("执行时间")
    private Date operateTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCmd() {
        return cmd;
    }

    public void setCmd(String cmd) {
        this.cmd = cmd;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public Integer getCmdType() {
        return cmdType;
    }

    public void setCmdType(Integer cmdType) {
        this.cmdType = cmdType;
    }

    public String getCmdTypeName() {
        return cmdTypeName;
    }

    public void setCmdTypeName(String cmdTypeName) {
        this.cmdTypeName = cmdTypeName;
    }

    public String getKafkaTopic() {
        return kafkaTopic;
    }

    public void setKafkaTopic(String kafkaTopic) {
        this.kafkaTopic = kafkaTopic;
    }

    public Date getOperateTime() {
        return operateTime;
    }

    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }
}