package com.vrv.vap.xc.pojo;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.vrv.vap.xc.model.BaseModel;
import com.vrv.vap.toolkit.annotations.NotNull;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table white_list
 *
 * @mbg.generated do_not_delete_during_merge 2020-11-30 17:17:44
 */
@ApiModel
@SuppressWarnings("unused")
public class WhiteList extends BaseModel {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *
     */
    @ApiModelProperty("")
    private String devid;

    /**
     *
     */
    @ApiModelProperty("")
    private String company;

    /**
     *
     */
    @ApiModelProperty("")
    private String number;

    /**
     *
     */
    @ApiModelProperty("")
    private String name;

    /**
     *
     */
    @ApiModelProperty("")
    @NotNull
    private String status;

    /**
     *
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("")
    private Date insertTime;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDevid() {
        return devid;
    }

    public void setDevid(String devid) {
        this.devid = devid;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getInsertTime() {
        return insertTime;
    }

    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }
}