package com.vrv.vap.admin.vo;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table base_personinfo
 *
 * @mbg.generated do_not_delete_during_merge 2018-08-09 10:24:00
 */
@ApiModel
@SuppressWarnings("unused")
public class BasePersoninfo extends PageModel{
	private int start_ = 0;
	private String count_="10";
    /**
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *   姓名
     */
    @ApiModelProperty("姓名")
    private String userName;

    /**
     *   性别
     */
    @ApiModelProperty("性别")
    private String sex;

    /**
     *   身份证号
     */
    @ApiModelProperty("身份证号")
    private String userIdnEx;

    /**
     *   人员类别:1警员2辅警3外单位人员
     */
    @ApiModelProperty("人员类别:1警员2辅警3外单位人员")
    private String personType;

    /**
     *   警员编号
     */
    @ApiModelProperty("警员编号")
    private String policeCode;

    /**
     *   警衔
     */
    @ApiModelProperty("警衔")
    private String policeRank;

    /**
     *   警衔代码
     */
    @ApiModelProperty("警衔代码")
    private String policeRankCode;

    /**
     *   职务
     */
    @ApiModelProperty("职务")
    private String policePost;

    /**
     *   职务代码
     */
    @ApiModelProperty("职务代码")
    private String policePostCode;

    /**
     *   职级
     */
    @ApiModelProperty("职级")
    private String policeLevel;

    /**
     *   职级代码
     */
    @ApiModelProperty("职级代码")
    private String policeLevelCode;

    /**
     *   机构号
     */
    @ApiModelProperty("机构号")
    private String orgCode;

    /**
     *   机构名称
     */
    @ApiModelProperty("机构名称")
    private String orgName;

    /**
     *   岗位
     */
    @ApiModelProperty("岗位")
    private String station;

    /**
     *   岗位名称
     */
    @ApiModelProperty("岗位名称")
    private String stationName;

    /**
     *   最后修改时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("最后修改时间")
    private Date lastUpdateTime;

    /**
     *   数据来源: 0第三方1人工添加
     */
    @ApiModelProperty("数据来源: 0第三方1人工添加")
    private String dataSource;

    /**
     *   修改状态: 0.未修改 1.已修改需提示:与同步数据不一致 2.已修改忽略不需提示:忽略同步数据
     */
    @ApiModelProperty("修改状态: 0.未修改 1.已修改需提示:与同步数据不一致 2.已修改忽略不需提示:忽略同步数据")
    private String isModify;

    /**
     *   上级ID,多个用逗号分隔
     */
    @ApiModelProperty("上级ID,多个用逗号分隔")
    private String parentId;

    /**
     *   年龄
     */
    @ApiModelProperty("年龄")
    private String age;

    /**
     *   警种编号
     */
    @ApiModelProperty("警种编号")
    private String policeTypeId;

    /**
     *   警种名称
     */
    @ApiModelProperty("警种名称")
    private String policeTypeName;

    /**
     *   省编码
     */
    @ApiModelProperty("省编码")
    private String provinceAreaCode;

    /**
     *   省名称
     */
    @ApiModelProperty("省名称")
    private String provinceAreaName;

    /**
     *   地市编码
     */
    @ApiModelProperty("地市编码")
    private String cityAreaCode;

    /**
     *   地市名称
     */
    @ApiModelProperty("地市名称")
    private String cityAreaName;

    /**
     */
    @ApiModelProperty("过滤id多个逗号分隔")
    private String filterId;

    public String getFilterId() {
        return filterId;
    }

    public void setFilterId(String filterId) {
        this.filterId = filterId;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getUserIdnEx() {
        return userIdnEx;
    }

    public void setUserIdnEx(String userIdnEx) {
        this.userIdnEx = userIdnEx;
    }

    public String getPersonType() {
        return personType;
    }

    public void setPersonType(String personType) {
        this.personType = personType;
    }

    public String getPoliceCode() {
        return policeCode;
    }

    public void setPoliceCode(String policeCode) {
        this.policeCode = policeCode;
    }

    public String getPoliceRank() {
        return policeRank;
    }

    public void setPoliceRank(String policeRank) {
        this.policeRank = policeRank;
    }

    public String getPoliceRankCode() {
        return policeRankCode;
    }

    public void setPoliceRankCode(String policeRankCode) {
        this.policeRankCode = policeRankCode;
    }

    public String getPolicePost() {
        return policePost;
    }

    public void setPolicePost(String policePost) {
        this.policePost = policePost;
    }

    public String getPolicePostCode() {
        return policePostCode;
    }

    public void setPolicePostCode(String policePostCode) {
        this.policePostCode = policePostCode;
    }

    public String getPoliceLevel() {
        return policeLevel;
    }

    public void setPoliceLevel(String policeLevel) {
        this.policeLevel = policeLevel;
    }

    public String getPoliceLevelCode() {
        return policeLevelCode;
    }

    public void setPoliceLevelCode(String policeLevelCode) {
        this.policeLevelCode = policeLevelCode;
    }

    public String getOrgCode() {
        return orgCode;
    }

    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getStation() {
        return station;
    }

    public void setStation(String station) {
        this.station = station;
    }

    public String getStationName() {
        return stationName;
    }

    public void setStationName(String stationName) {
        this.stationName = stationName;
    }

    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    public String getDataSource() {
        return dataSource;
    }

    public void setDataSource(String dataSource) {
        this.dataSource = dataSource;
    }

    public String getIsModify() {
        return isModify;
    }

    public void setIsModify(String isModify) {
        this.isModify = isModify;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public String getPoliceTypeId() {
        return policeTypeId;
    }

    public void setPoliceTypeId(String policeTypeId) {
        this.policeTypeId = policeTypeId;
    }

    public String getPoliceTypeName() {
        return policeTypeName;
    }

    public void setPoliceTypeName(String policeTypeName) {
        this.policeTypeName = policeTypeName;
    }

    public String getProvinceAreaCode() {
        return provinceAreaCode;
    }

    public void setProvinceAreaCode(String provinceAreaCode) {
        this.provinceAreaCode = provinceAreaCode;
    }

    public String getProvinceAreaName() {
        return provinceAreaName;
    }

    public void setProvinceAreaName(String provinceAreaName) {
        this.provinceAreaName = provinceAreaName;
    }

    public String getCityAreaCode() {
        return cityAreaCode;
    }

    public void setCityAreaCode(String cityAreaCode) {
        this.cityAreaCode = cityAreaCode;
    }

    public String getCityAreaName() {
        return cityAreaName;
    }

    public void setCityAreaName(String cityAreaName) {
        this.cityAreaName = cityAreaName;
    }

	public String getCount_() {
		return count_;
	}

	public void setCount_(String count_) {
		this.count_ = count_;
	}

	public int getStart_() {
		return start_;
	}

	public void setStart_(int start_) {
		this.start_ = start_;
	}
    
}