package com.vrv.vap.line.model;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table label_red
 *
 * @mbg.generated do_not_delete_during_merge 2018-10-09 09:34:28
 */
@ApiModel("标签热点")
public class LabelRedModel {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;

    /**
     *
     */
    @ApiModelProperty("")
    private String labelName;

    /**
     *
     */
    @ApiModelProperty("")
    private Long count;

    /**
     *
     */
    @ApiModelProperty("")
    private String objType;

    /**
     *
     */
    @ApiModelProperty("")
    private String type;

    /**
     *
     */
    @ApiModelProperty("")
    private String labelConfId;

    /**
     *
     */
    @ApiModelProperty("")
    private Integer yesterdayRank;


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getLabelName() {
        return labelName;
    }

    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    public Long getCount() {
        return count;
    }

    public void setCount(Long count) {
        this.count = count;
    }

    public String getObjType() {
        return objType;
    }

    public void setObjType(String objType) {
        this.objType = objType;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getLabelConfId() {
        return labelConfId;
    }

    public void setLabelConfId(String labelConfId) {
        this.labelConfId = labelConfId;
    }

    public Integer getYesterdayRank() {
        return yesterdayRank;
    }

    public void setYesterdayRank(Integer yesterdayRank) {
        this.yesterdayRank = yesterdayRank;
    }

}