# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 19562
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值25
      minSpare: 30

logging:
  level:
    com.vrv.vap: debug
    root: info
    com.alibaba.nacos: ERROR
    #    com.vrv.vap.user.mapper: debug
    org.springframework: warn

spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  cloud:
    nacos:
      config:
        server-addr: ${SERVER_ADDR}
        namespace:   ${NAMESPACE}
        file-extension: yml
      discovery:
        server-addr: ${SERVER_ADDR}
        namespace: ${NAMESPACE}
        enabled: true
SERVER_ADDR: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
NAMESPACE: ${NACOS_NAMESPACE:a338c762-d2a7-4a2f-86f0-022c171c0928}
