package com.vrv.vap.amonitor.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table label_conf
 *
 * @mbg.generated do_not_delete_during_merge 2018-09-30 17:40:24
 */
@ApiModel
@SuppressWarnings("unused")
public class LabelConf extends PageModel {
    /**
     *
     */
    @ApiModelProperty("")
    private Integer id;
    @ApiModelProperty("多条数据")
    private String ids;

    /**
     * 标签名称
     */
    @ApiModelProperty("标签名称")
    private String name;

    /**
     * 创建时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("创建时间")
    private Date createTime;

    /**
     * 更新时间
     */
    @JsonFormat(timezone = "GMT+8", pattern = "yyyy-MM-dd HH:mm:ss")
    @ApiModelProperty("更新时间")
    private Date updateTime;

    /**
     * 0 人 1 设备  2 应用
     */
    @ApiModelProperty("0 人 1 设备  2 应用   ")
    private String objType;

    /**
     * 业务场景类别 0 基于模型 1 基于规则二 2 基于统计分析 3 自定义
     */
    @ApiModelProperty("业务场景类别 0 基于模型 1 基于规则二 2 基于统计分析 3 自定义 ")
    private String type;

    /**
     * 创建人id
     */
    @ApiModelProperty("创建人id")
    private String createId;

    /**
     * 创建人姓名
     */
    @ApiModelProperty("创建人姓名")
    private String createName;
    /**
     * 关联（人，设备，应用）数
     */
    @ApiModelProperty("关联（人，设备，应用）数")
    private long number;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getCreateTime() {
        return createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getObjType() {
        return objType;
    }

    public void setObjType(String objType) {
        this.objType = objType;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getCreateId() {
        return createId;
    }

    public void setCreateId(String createId) {
        this.createId = createId;
    }

    public String getCreateName() {
        return createName;
    }

    public void setCreateName(String createName) {
        this.createName = createName;
    }

    public String getIds() {
        return ids;
    }

    public void setIds(String ids) {
        this.ids = ids;
    }

    public long getNumber() {
        return number;
    }

    public void setNumber(long number) {
        this.number = number;
    }
}